name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.x, 2.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install setuptools wheel
      - name: Build serialiJSON
        run: |
          python setup.py sdist bdist_wheel
      - name: Install serialiJSON
        run: |
          pip install dist/serialiJSON-*.tar.gz
      - name: Run tests
        run: |
          python tests/test.py
